.. -*- rst -*-
.. vim: ft=rst
.. Links and substitutions that might be used on more than one page

.. Version control
.. _git: http://git-scm.com
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com
.. _bitbucket: https://bitbucket.org/

.. Editors
.. _vim: http://www.vim.org
.. _command-t: https://wincent.com/products/command-t
.. _command-t README: http://git.wincent.com/command-t.git/blob_plain/master:/README.txt

.. Python and common libraries
.. _python: http://www.python.org
.. _python.org releases: http://www.python.org/download/releases
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: http://pypi.python.org/pypi/pip
.. _numpy: http://sourceforge.net/projects/numpy/files
.. _scipy: http://sourceforge.net/projects/scipy/files
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _sphinx: http://www.sphinx-doc.org
.. _rest:
.. _restructuredtext: http://docutils.sourceforge.net/rst.html

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _pypi: http://pypi.python.org
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _homebrew: https://brew.sh/
.. _macports: http://www.macports.org
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: http://macvim-dev.github.io/macvim/
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com
.. _flat package format: http://s.sudre.free.fr/Stuff/Ivanhoe/FLAT.html
.. _unpacking flat packages:
   http://ilostmynotes.blogspot.com/2012/06/mac-os-x-pkg-bom-files-package.html
.. _mactech flat package article:
    http://www.mactech.com/articles/mactech/Vol.26/26.02/TheFlatPackage/index.html
.. _software delivery legacy guide:
    https://developer.apple.com/legacy/library/documentation/DeveloperTools/Conceptual/SoftwareDistribution4/Introduction/Introduction.html
.. _distribution definition file:
    https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Introduction.html#//apple_ref/doc/uid/TP40005370-CH1-SW1
.. _install operations:
    https://developer.apple.com/legacy/library/documentation/DeveloperTools/Conceptual/SoftwareDistribution4/Install_Operations/Install_Operations.html
.. _installer javascript reference:
    https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/InstallerJavaScriptRef/InstallerJavaScriptRef.pdf
.. _stackoverflow package building answer:
    http://stackoverflow.com/questions/11487596/making-os-x-installer-packages-like-a-pro-xcode4-developer-id-mountain-lion-re/11487658#11487658


.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty
.. _windows compiler tools:
    http://matthew-brett.github.com/pydagogue/develop_windows#win-compile-tools

.. Nipy and friends
.. _nipy: http://nipy.org
.. _gitwash: http://github.com/matthew-brett/gitwash

.. Licenses
.. _CC0 license: http://creativecommons.org/publicdomain/zero/1.0/legalcode

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
